sudo: false
dist: trusty
language: python
notifications:
  email: false
python:
  - "3.8"
  - "3.7"
  - "3.6"
install:
  - python setup.py install
  - python -c "import sqlite3 as sqlite; print(sqlite.sqlite_version)"
script: make test-all
