sudo: false
dist: bionic
language: python
notifications:
  email: false
python:
  - "3.8"
  - "3.7"
  - "3.6"
install:
  - pip install flake8
  - python setup.py install
  - python -c "import sqlite3 as sqlite; print(sqlite.sqlite_version)"
script:
  - flake8 sqldict
  - make test-all
